language: csharp
solution: BinaryTree.sln


addons:
  sonarcloud:
    organization: "f8wc5bca"
    token:
      secure: "AvTibzpDg47gQgbsfc9fiYr78jtA5Y2rAq0OhTEJ/B1OWJ32qPPWy8D8oJWLrOzPm+tQianHk+l/raG1bDZXiKSBNLk1cdda/Yvm6bMYmxiDUCLLfEHrR1/2Ncrb7dQkF7ISdlBl5+gDRSNYi7czu4vyHM6FvcP1/eUxDG/EhuvNox2IoLY0Ak6i92BKGN9Onc54ZX2YNySDA76nUMp1VJzT6YMiFMDDQHdUhGdvf3kjEllMUFqK4sNkD0yE/WkHeeyanF52BXgaLVRoHVg/2lWvIHGqS8RgoTjj+jw6b7exlktnobnjPVJVJg5fo6nZ872akn4N/leBFrZD5pZ105b4kxUZLCkI1vOFG80YeNh3XbvzRMHrJm6+JgBddq10n5rT8qo4DV3QmDs08aZgj6MicNYKlPNDJWJ5KCEwk5kOiP3fGBX9wwtrvSO9ZazWIpVA6okDLgIbXvbk3esX+vcFeHfZ+yXRNLxRxlL68NrljOwB7ieB+JNqc2tgmPbdj4kmkxrwPpUueKAwHXFRzE/GnATNUiOyeb+joZOyoX9qqMjlmWty05wt6SxZ448gU3QoMuuAYlIpRE/XcqVqOVLxiMqhiyFxSLJKmkbG7Kn3ARscgZQ177nJLCNM39otGuHAptU7jX4x0SZMP5rq7bfXHSyaNrVY6YtOfPC9NMc=" # encrypted value of your token

script:
  # the following command line builds the project, runs the tests with coverage and then execute the SonarCloud analysis
  - sonar-scanner
